query {
  getAllOutlets {
    _id
    uniqueId
    name
    location
    assignedSalesman {
      firstName
      lastName
    }
    owner {
      firstName
      lastName
    }
    outletContact {
      telephone
    }
  }
}
