query($salesman_id: ID!, $date: String!) {
  getJourneyPlanForSalesman(salesman_id: $salesman_id, date: $date) {
    _id
    outlets {
      order
      outlet {
        _id
        uniqueId
        name
        location
        owner {
          firstName
          lastName
        }
        outletContact {
          telephone
        }
      }
    }
  }
}
